// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZYCSo0rvcMJTl7GUGG4Hw2debzH9ZJus',
    appId: '1:19880098284:web:34a10f950bf9f7af4868c9',
    messagingSenderId: '19880098284',
    projectId: 'fir-testing-47026',
    authDomain: 'fir-testing-47026.firebaseapp.com',
    storageBucket: 'fir-testing-47026.appspot.com',
    measurementId: 'G-N658S1787H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzXTtngFPWVlPUJg58-IGBVEJLnx2inEs',
    appId: '1:19880098284:android:0fa40f7082cfeafc4868c9',
    messagingSenderId: '19880098284',
    projectId: 'fir-testing-47026',
    storageBucket: 'fir-testing-47026.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCROWuDzLr4FwnQS55crrS1jOJ3HfatQy4',
    appId: '1:19880098284:ios:a6b1244c7abbc5194868c9',
    messagingSenderId: '19880098284',
    projectId: 'fir-testing-47026',
    storageBucket: 'fir-testing-47026.appspot.com',
    iosClientId:
        '19880098284-g5c92ti9a5ruaf7sktgoevtjr2disie3.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
